docs: getting started
near/chain-hosted-ui pull request #56
Opened 2024-07-29 23:30 UTC by andy-haynes

This PR adds a `Getting Started` section to the project README with instructions on how to deploy an application using the monorepo.

2024-07-29 23:31 UTC, andy-haynes commented on README.md
> +5. Load the application at `http://ec2-54-185-81-147.us-west-2.compute.amazonaws.com/FILE_CONTRACT.near/DEPLOYER_ACCOUNT.near/APPLICATION-NAME` (with `FILE_CONTRACT` being `pfs1.testnet` or `v1.chain
This requires a forthcoming `cdn` update 😅

2024-07-30 15:16 UTC, mpeterdev requested changes

2024-07-30 15:16 UTC, mpeterdev commented on README.md
> +2. Configure the `nearDeployConfig` field in `package.json`:
add step in between 1&2 to cd into `packages/react` or `packages/vue`

2024-07-30 15:16 UTC, mpeterdev commented on README.md
> +   2. `deployerAccount` is the account paying for bundle storage and calling smart contract methods (must match `DEPLOYER_ACCOUNT.near` referenced above)
```suggestion
   2. `deployerAccount` is your account that pays for bundle storage and calls smart contract methods. This corresponds to the keystore created above (must match `DEPLOYER_ACCOUNT.near`)
```

2024-07-30 15:16 UTC, mpeterdev commented on README.md
> +   3. `filestoreContract` is the hosted storage contract (`pfs1.testnet` on testnet and `v1.chainui.near` on mainnet, or deployed and configured separately)
```suggestion
   3. `filestoreContract` is the chain-hosted-ui contract (`pfs1.testnet` on testnet and `v1.chainui.near` on mainnet, or deployed and configured separately)
```

2024-07-30 15:16 UTC, mpeterdev commented on README.md
> +4. Run `pnpm run deploy` to build the project bundle and deploy the application on chain.
```suggestion
4. Run `pnpm run deploy` to build the project bundle and deploy the application on chain. You will be presented with the estimated cost to approve before executing the deploy
```

2024-07-30 17:12 UTC, mpeterdev approved these changes

2024-07-30 17:12 UTC, merged